#include <iostream>
#include <vector>
#include <cmath>
#include <string>

// g++ -std=c++20 -pedantic -Wall -Wextra -Werror -Wshadow -Wsign-conversion -g sandbox.cpp  -o sandbox
// g++ -std=c++20 -pedantic -Wall -Wextra -Wsign-conversion -g sandbox.cpp -o sandbox
// <br />
// PLACEHOLDEREXERCISENAME < input.txt > output.txt
// PLACEHOLDEREXERCISENAME ./exercise5 < input.txt >> output.txt
// Redirection in powershell  Get-Content .\input.txt | .\<YOUREXERCISENAME>>.exe
using std::cout;
using std::endl;
using std::vector;
using std::string;
using std::cin;


int main()
{

    /* (a) A class must provide at least one constructor.
    (b) A default constructor is a constructor with an empty parameter list.
    (c) If there are no meaningful default values for a class, the class should not
    provide a default constructor.
    (d) If a class does not define a default constructor, the compiler generates
    one that initializes each data member to the default value of its associated
    type. */

    // (a) Not true, a class does not necessarily have to have a constructor, in some cases
    // it will be synthesized for the class

    // (b) Not true, a default constructor is a constructor which can be called with no arguments.
    // It can have parameters but they have to have default values

    // (c) Lack of context, I'd say true


    // (d) Untrue, there must be NO constructor inside a class for the default constructor to be generated by the compiler

    return 0;
}
